apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: foodie

resources:
  - namespace.yaml
  - secrets.yaml
  - configmaps.yaml
  - platform.yaml
  - observability/prometheus.yaml
  - observability/otel-collector.yaml
  - observability/jaeger.yaml
  - observability/tempo.yaml
  - observability/grafana.yaml
