---
apiVersion: v1
kind: Secret
metadata:
  name: foodie-db-credentials
  namespace: foodie
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "root"

---
apiVersion: v1
kind: Secret
metadata:
  name: razorpay-credentials
  namespace: foodie
type: Opaque
stringData:
  RAZORPAY_KEY_ID: "rzp_test_local_dummy"
  RAZORPAY_KEY_SECRET: "local_dummy_secret"
  RAZORPAY_WEBHOOK_SECRET: "local_dummy_webhook_secret"

---
apiVersion: v1
kind: Secret
metadata:
  name: foodie-jwt-secret
  namespace: foodie
type: Opaque
stringData:
  JWT_SECRET: "local-development-jwt-secret-change-before-prod-123456"

---
apiVersion: v1
kind: Secret
metadata:
  name: foodie-internal-secret
  namespace: foodie
type: Opaque
stringData:
  USER_SERVICE_INTERNAL_SECRET: "local-internal-shared-secret"
